---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
    volumes:
      - ./config:/config
      - ~/media/movies:/movies #optional
      - ~/media:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
