---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- resources:
    cpu: true
    memory: true
    expanded: true
    cputemp: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    uptime: true
    disk:
      - /
      - /mnt/media

- openmeteo:
    label: Split # optional
    latitude: 43.508133
    longitude: 16.440193
    timezone: Europe/Zagreb # optional
    units: metric # or imperial
    cache: 30 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- datetime:
    text_size: lg
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
